version: "3"

services:
  localstack:
    image: localstack/localstack
    container_name: stonks_nlp_localstack
    ports:
      - "4567-4599:4567-4599"
    environment:
      - SERVICES=serverless
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  stonks_nlp:
    container_name: stonks_nlp
    build: .
    command: tail -F anything # Prevents container from immediately closing
    volumes:
      - ./:/code
